describe('Testar Página Inicial', () => {
  it('Deve acessar e validar a página inicial', () => {
    cy.visit('https://automationexercise.com/')
    cy.contains('Full-Fledged practice website for Automation Engineers')
      .should('be.visible')

    cy.contains('Signup / Login').click()
    cy.contains('New User Signup!').should('be.visible')
    cy.get('[data-qa="signup-name"]').type('Victor Figueiredo')
    cy.get('[data-qa="signup-email"]').type('final.bsi@gmail.com')
    cy.get('[data-qa="signup-button"]').click()
    cy.contains('Enter Account Information')
      .should('be.visible')
    cy.get('#id_gender1').click()
    cy.get('[data-qa="name"]').should('have.value', 'Victor Figueiredo')
    cy.get('[data-qa="email"]').should('have.value', 'final.bsi@gmail.com')
    cy.get('[data-qa="password"]').type('654321')
    cy.get('#days').select('11')
    cy.get('#months').select('February')
    cy.get('#years').select('1989')
    cy.get('label[for="newsletter"]').click()
    cy.get('label[for="optin"]').click()
    cy.get('[data-qa="first_name"]').type('Victor')
    cy.get('[data-qa="last_name"]').type('Victor')
    cy.get('[data-qa="company"]').type('Victor QA Automation')
    cy.get('[data-qa="address"]').type('Rua Josino Antunes da Silva')
    cy.get('[data-qa="address2"]').type('Nº 95. Curva do Rio')
    cy.get('[data-qa="country"]').select('United States')
    cy.get('[data-qa="state"]').type('Minas Gerais')
    cy.get('[data-qa="city"]').type('Unai')
    cy.get('[data-qa="zipcode"]').type('38.620-874')
    cy.get('[data-qa="mobile_number"]').type('(38) 9.9970-6879')
    cy.get('[data-qa="create-account"]').click()

    cy.get('p')
      .contains('Congratulations! Your new account has been successfully created!')
      .should('be.visible')

    cy.get('[data-qa="continue-button"]').click()
    cy.contains('a', 'Logged in as', { timeout: 10000 })
      .should('be.visible')
      .find('b')
      .should('contain', 'Victor')

    cy.get('a[href="/delete_account"]').click()

    cy.get('p')
      .contains('Your account has been permanently deleted!')
      .should('be.visible')
  })
})
