name: Pipeline CI Cypress com Allure

on:
  push:
    branches: [ main, master, nova-versao ]
  pull_request:
    branches: [ main, master, nova-versao ]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests with Allure
        run: npm run cy:run

      - name: Generate Allure Report
        run: npm run allure:generate

      - name: Upload Allure Report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      # Opcional: Expor o relatório como página estática (ver docs do Allure + GitHub Pages)
